export const MENU_ACTION_TYPES = {
    FETCH_CATEGORIES_START: 'menu/FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'menu/FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILED: 'menu/FETCH_CATEGORIES_FAILED'
    
}